### ISSUE TITLE
expose a method to reload stevedore cache

### ISSUE THREAD

**Issue by theorm** [DHARPA-Project/kiara#12]
Lumy middleware has a capability to install python dependencies on the fly from within the main process. Stevedore used for both kiara and lumy modules resolves and caches all plugins found in the Python environment on first load. Stevedore does not provide a public method to invalidate this cache. To get around this Lumy middleware reloads stevedore package entirely to make it reinitialise the cache (see this [PR](https://github.com/DHARPA-Project/lumy-middleware/pull/20)). This works fine for Lumy modules but it probably won't work for Kiara which has its own instance of stevedore. We will need a public function provided by Kiara that would invalidate stevedore cache for Kiara modules.

**Comment by makkus** [comment]
Have you tested this and can you confirm that it doesn't work? kiara does nothing different, just `import stevedore`, so I don't understand how an `importlib.reload(stevedore)` wouldn't also reload the kiara stevedore cache.

You will have to create a new kiara instance though, kiara assumes that available modules (and most other things) are static within the lifetime of a kiara instance. It'd be possible to make that more dynamic, but that would complicate the code by an order of magnitude, and it would make everything a lot more fragile, so I don't think the effort would be worth it.

**Comment by theorm** [comment]
It looks like Kiara does not want to be recreated. When an instance is created, a ZMQ port is allocated and a logging thread is started (see [here](https://github.com/DHARPA-Project/kiara/blob/0.0.4/src/kiara/kiara.py#L75-L76)). The start methods are there, but there are no stop methods.

Can you please provide instructions how to recreate a Kiara instance.

**Comment by makkus** [comment]
Yeah, that's a known bug, sorry. In the newer versions I've just commented those two lines out because nothing relies on the zmq stuff yet, you might have to do that in a local copy of that version of the kiara code since you can't use the newer versions and I'm not back to work for at least two more weeks. I did that a while ago, so I can't remember whether there is any other part of the code that needs to be commented out, but a quick 'grep zmq' would probably be enough to find any potential instances if something errors out.

Btw, I think updating a Python environment at runtime is quite a daring thing to do, there is a lot that can go wrong even if there isn't any 'fancy' classloading involved (and most of the scientific packages do have 'fancy' classloading and a lot of global state). Personally, I wouldn't do it, but as long as you know what you are doing...

Kiara will also use a snapshot of all installed packages and their versions in the current virtual environment as a hash that is attached to every value that was created in a kiara context. It might be that just using a new instance of Kiara will be enough to not run into problems (since that will re-create the environment hash), but I can't guarantee that. I'm not a good enough Python developer to feel confident to be able to write reliable code in a non-static Python-env scenario (and I'm not sure it's possible at all), so I would advise to have good and extensive testing around all of this.

**Comment by theorm** [comment]
I think in Lumy we should use a dedicated kernel running a workflow within its own virtual environment. Once we do this, there will be one main Python kernel running with a kiara instance that will be used to work with data repository, and one side Python kernel running current workflow, that can be recreated when a new workflow is loaded.  I'm not sure what implications it will have on data repository but we are not going to restart the main kernel in Lumy, so that's for Kiara developer to take care of.

That's for future. For now in middleware after stevedore cache is updated I'm just going to do:

```
Kiara.instance()._module_mgr = MergedModuleManager(
    Kiara.instance()._config.module_managers
)
```

because I need to get this working in Lumy now.

**Comment by makkus** [comment]
Ok, if that works, great.

**Comment by theorm** [comment]
No it doesn't. It throws a `NotImplemented` exception here: https://github.com/DHARPA-Project/kiara/blob/0.0.4/src/kiara/utils/class_loading.py#L205

Since this exception does not provide any details, I can't see which module causes it. This happens even if no new modules are installed. 

I can create a separate issue for this, but for now I may need to fork kiara `0.0.4` and use it in Lumy builds until this is fixed in the latest version of Kiara along with [this issue](https://github.com/DHARPA-Project/kiara/issues), that will let us upgrade to a later version of Kiara.

**Comment by makkus** [comment]
Yes, I'll look at both of those once I'm back. And yes, best to create a new issue for the other thing, and it'd be great if it had some example code so I can replicate the exact same issue. I've got a better test setup now, so it'll be easy to add all of those issues as tests from now on once they are fixed, and having that example code will make that easier.

**Comment by theorm** [comment]
@makkus https://github.com/DHARPA-Project/kiara/issues/13
