### ISSUE TITLE
Include asciinet as dependency

### ISSUE THREAD

**Issue by stakats** [DHARPA-Project/kiara#29]
To discuss. It may not be worth it with other, better visualization coming online. But if we expect people to try this regularly from CLI, it needs to be installed to visualize data-flow-graph

**Comment by makkus** [comment]
It doesn't have a proper pypi package released, so it's hard to include by default since pip would have to install it using git during setup which brings a chance the whole install could fail in certain situations. In addition, it requires Java to be installed, which in theory we could do with conda, but it'd blow up the initial install size quite a bit if we did. 
Also, the project hasn't seen any commit since 2017, which made me hesitant to depend on it. It works well enough, and it's the best of the alternatives I could find for the command-line that didn't require me to do a lot of work, which is why I added it initially, but if we want that functionality, I'd feel better if we either find something else, or implement something ourselves.

Maybe I'm overly careful though, dunno.

**Comment by makkus** [comment]
Ok, I went with a compromise: I built a Python package of asciinet myself and uploaded it to Pypi. Since it includes a 12MB java package, I didn't want to include it into he kiara package by default, because in most cases its not needed. But if a user calls any of the 'explain pipeline graph' sub-commands, kiara will try to auto download and install that package transparently, on demand.

It will still fail if Java is not installed, but installing Java is out of scope and we don't really want to do that on a users computer without them knowing. So kiara will just print an error message to that effect, and lets the user know they need to install a JRE.
