### ISSUE TITLE
Add date and time as metadata for data items added to data store/archive

### ISSUE THREAD

**Issue by MariellaCC** [DHARPA-Project/kiara#70]
It may be helpful for users to have the information recorded of when a data item was added to the data store/archive.

Additionally, being able to access this date/time info with the data item name and size when doing `kiara data list` might also help visually identify some data items quicker.

**Comment by makkus** [comment]
This is going to be a bit tricky, as there are different times we could record:

- when the item was created within a kiara session -- this could be a source of confusion for users, because kiara might return a previously computed value if the same computation has been run before (but either they forgot, or imported some values from other other peoples stores) -- in which case the time displayed could be days/weeks/months before a user even started to use kiara

- when the item was persisted in a store (what should happen if it is then stored in another store, what time should we record)?

I guess I can store 2 values: one creation, and one when it was persisted in each store, as long as someone says it's ok and we don't worry about potentially confusing users.

**Comment by MariellaCC** [comment]
I think the expectation from a user's perspective (this came out from a user test) is to see something as they have on their computer: "I added this "file" (in the computer files analogy) that day at that time, and the file's name is file_name and it has a size of ...". The list via `kiara data list` already includes some information that this user expected like name and size, but they were also expecting to find a date/time.

This doesn't answer your questions but I thought I would add a bit more context.

I will experiment more with the kiara sessions as I am not familiar with them at the moment, and maybe we could keep this open for another user test round where users would be introduced to kiara sessions (which was not the case previously) when we have an updated tutorial ready to test?

**Comment by makkus** [comment]
Ok, in this case I think the 'when was it stored' is probably best? It's a bit like the 'last modified' time you'd see on a traditional filesystem.

**Comment by makkus** [comment]
For non-stored values that field would be empty, but that's probably ok I guess.

**Comment by MariellaCC** [comment]
> Ok, in this case I think the 'when was it stored' is probably best? It's a bit like the 'last modified' time you'd see on a traditional filesystem.

Yes, I guess so.

**Comment by makkus** [comment]
For the record: there can be times when a value lives in a kiara sessions twice: for example when you import it from a store, then 'export'/save it to another one (for example from an external store to your 'default' store). In this case I'll try to always use the earlier of the two times (I hope, but can't guarantee yet, that this will be possible in all cases).

Edge case, but those need to be well defined...

**Comment by makkus** [comment]
Ok, I've added a first implementation for this, but after our discussion in the last meeting I decided to use the 'created' date after all. I won't consider this stable in the next version of *kiara*, but include it in the release, so people can try it out for the things they have in mind, and provide feedback etc.
