### ISSUE TITLE
Kiara instance data registry is not updated after new items are saved

### ISSUE THREAD

**Issue by theorm** [DHARPA-Project/kiara#8]
Example:

```python
from kiara import Kiara

kiara = Kiara.instance()

w = kiara.create_workflow('table.from_csv', workflow_id='moo3')
w.inputs.set_values(path='/content/sample_data/california_housing_test.csv')

for field, value in w.outputs.items():
  value_type = value.type_obj
  save_config = value_type.save_config()

  if save_config is not None:
    value_id = value.save()
    print(f'Saved: {field} - {value_id}')

print(list(kiara.data_store.value_ids))
```

The output is `[]`, however I expected the newly saved table to be in this list.

I understand that there is some caching happening in `kiara.data_store` which I would expect to be updated/invalidated. In Lumy we can even invalidate this cache manually, but I cannot find a way to do it.

**Comment by makkus** [comment]
Right, yes, that wasn't a problem so far with the cli since it would pick up the updated list with every new invocation of kiara. But I can see how one might want that for a longer-running app :-)

It'll probably take me until the end of the week to get to this because the DataStore class is under construction currently, as a workaround you could (as you suggested) do it manually for now. I haven't tested this, but basically it would be something like:

    kiara_obj.data_store._value_id_cache = None

(whenever you want to clear the cache)

Let me know if that doesn't work.

**Comment by theorm** [comment]
Thanks Markus. I think it's ok to wait. I built a new version of Lumy yesterday and I don't think there will be a new built before this part is fixed.

**Comment by makkus** [comment]
@theorm , can you check whether this works now?

**Comment by makkus** [comment]
Closing this, since the DataStore class has been re-written, and doesn't do caching anymore.
